# Jekyll
remote-theme: benbalter/retlab #linkhub-jekyll-theme

# Site Configuration
name: Sigwo Group # Name of your website
tagline: Hi  # Set your preferred page title
description:  Welcome! # Also used as a meta description
favicon: https://www.sigwoindustries.com/web/image/website/1/favicon?unique=bb0cf10 # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
logo: https://www.sigwoarms.com/web/image/5369-6015a3f6/IMG_0134.PNG # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://www.sigwoindustries.com/r/oI6 # URL of your website
locale: en_GB # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
ga4: G-7VWD9Q6VJH # Google Analytics 4 measurement ID (optional). Remove it if not needed.
twitter:
  username: sigwoarms # Used for SEO
image:
  path: https://www.sigwoindustries.com/web/image/website/1/logo/Sigwo%20Industries?unique=bb0cf10 # Used for SEO
  type: jpeg # File format of image. Change according to your image. Supported types: https://en.wikipedia.org/wiki/Media_type#Common_examples
  height: 100 # Pixels
  width: 100
  alt: logo

# Verified Badge Configuration
badge: false  # Set to 'true' or 'false' to enable / disable the badge
icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
